-- AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Run after 0001_init.sql. Re-run the generator to regenerate.
-- The first lesson is a free preview using Mux's public demo video so it plays
-- before you upload your own videos.

do $$
declare v_course uuid; v_module uuid; v_quiz uuid;
begin
  delete from public.courses where slug = 'oracle-fusion-ai-agent-studio';
  insert into public.courses (slug, title, subtitle, description, thumbnail_url, price_cents, currency, level, instructor_name, duration_hours, highlights, outcomes, published)
  values ('oracle-fusion-ai-agent-studio', 'Oracle Fusion AI Agent Studio — Complete Course 2026', '25 Modules · 15 Real Enterprise Projects · 50–70 Hours', 'A comprehensive 50–70 hour professional training program for Oracle consultants, integration architects, and AI specialists. Go from AI fundamentals to advanced enterprise-grade AI Agent implementations inside Oracle Fusion Cloud. Build real-world AI Agents that integrate with Oracle Fusion HCM, ERP, OIC, UCM, and external systems including GitHub, Azure DevOps, SharePoint, Microsoft Teams, and Slack — using the full suite of Oracle AI Studio tools: Business Object Tool, External REST Tool, MCP Tool, Workflow Designer, and Hierarchical Agent patterns.', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80', 19900, 'usd', 'advanced', 'Umasankar Ratnala', '50–70 hours', '[{"label":"Modules","value":"25"},{"label":"Projects","value":"15"},{"label":"Hours","value":"50–70"},{"label":"Bonus","value":"13+"}]'::jsonb, '["Design and build AI Agents in Oracle Fusion AI Agent Studio from scratch","Configure prompts, personas, topics, and tools for enterprise use cases","Integrate agents with Oracle Fusion (HCM, ERP), OIC, UCM, HDL, REST/SOAP, GitHub, Azure DevOps","Develop Workflow and Hierarchical Agent solutions with the Workflow Designer","Implement enterprise security (OAuth 2.0, JWT, Guardrails), monitoring (METRO), and deployment","Build and deploy 15 real-world AI automation projects for HCM and ERP","Apply MCP to connect Oracle AI Agents to external LLMs and dev tools","Implement RAG with vector databases for AI Knowledge Assistants"]'::jsonb, true)
  returning id into v_course;
  insert into public.modules (course_id, title, position) values (v_course, 'Introduction to Artificial Intelligence', 0) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'What is Artificial Intelligence?', 'qxb01i6T202018GFS02vp9RIe01icTcDCjVzQpfab00CUxg', 0, true),
    (v_module, 'Machine Learning vs Deep Learning', null, 1, false),
    (v_module, 'Generative AI', null, 2, false),
    (v_module, 'Large Language Models (LLMs)', null, 3, false),
    (v_module, 'Prompt Engineering Basics', null, 4, false),
    (v_module, 'AI Agents', null, 5, false),
    (v_module, 'Agentic AI', null, 6, false),
    (v_module, 'Enterprise AI & Oracle AI Strategy', null, 7, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Introduction to Oracle Fusion AI Agent Studio', 1) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'What is Oracle Fusion AI Agent Studio?', null, 0, false),
    (v_module, 'AI Agent Studio Architecture', null, 1, false),
    (v_module, 'Licensing', null, 2, false),
    (v_module, 'Features & Use Cases', null, 3, false),
    (v_module, 'Supported Oracle Fusion Pillars', null, 4, false),
    (v_module, 'AI Studio Navigation', null, 5, false),
    (v_module, 'Environment Setup', null, 6, false),
    (v_module, 'DEMO: Enable AI Agent Studio & navigate Agents, Tools, Topics, Monitoring', null, 7, false);
  insert into public.modules (course_id, title, position) values (v_course, 'AI Agent Studio Components', 2) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Agent Team', null, 0, false),
    (v_module, 'Agents', null, 1, false),
    (v_module, 'Topics', null, 2, false),
    (v_module, 'Tools', null, 3, false),
    (v_module, 'Instructions', null, 4, false),
    (v_module, 'Testing', null, 5, false),
    (v_module, 'Deployments', null, 6, false),
    (v_module, 'Monitoring', null, 7, false),
    (v_module, 'LAB: Build your first AI Agent from scratch', null, 8, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Understanding AI Agents', 3) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'User Proxy Agent', null, 0, false),
    (v_module, 'Supervisor Agent', null, 1, false),
    (v_module, 'Specialist Agent', null, 2, false),
    (v_module, 'Utility Agent', null, 3, false),
    (v_module, 'Persona-based Agent', null, 4, false),
    (v_module, 'Task-oriented Agent', null, 5, false),
    (v_module, 'Tool User Agent', null, 6, false),
    (v_module, 'LAB: Create each of the seven agent types', null, 7, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Agentic Design Patterns', 4) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Single Agent', null, 0, false),
    (v_module, 'Multi-Agent', null, 1, false),
    (v_module, 'Hierarchical Agents', null, 2, false),
    (v_module, 'Workflow Agents', null, 3, false),
    (v_module, 'Supervisor Pattern', null, 4, false),
    (v_module, 'Human in the Loop', null, 5, false),
    (v_module, 'Agent-to-Agent (A2A)', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Prompt Engineering', 5) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Prompt Fundamentals', null, 0, false),
    (v_module, 'Persona, Role, Goal', null, 1, false),
    (v_module, 'Instructions & Constraints', null, 2, false),
    (v_module, 'Guardrails', null, 3, false),
    (v_module, 'Hallucination Prevention', null, 4, false),
    (v_module, 'Summarisation & System Prompts', null, 5, false),
    (v_module, 'Prompt Chaining', null, 6, false),
    (v_module, 'Dynamic Prompts', null, 7, false),
    (v_module, 'LAB: Debug & improve prompts', null, 8, false);
  insert into public.modules (course_id, title, position) values (v_course, 'AI Agent Tools — Overview', 6) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Tools overview', null, 0, false),
    (v_module, 'Calculator Tool', null, 1, false),
    (v_module, 'Email Tool', null, 2, false),
    (v_module, 'Deep Link Tool', null, 3, false),
    (v_module, 'User Session Tool', null, 4, false),
    (v_module, 'Connector Tool', null, 5, false),
    (v_module, 'Document Tool', null, 6, false),
    (v_module, 'User Query Tool', null, 7, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Business Object Tool', 7) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Create Business Object Tool', null, 0, false),
    (v_module, 'Input & Output Variables', null, 1, false),
    (v_module, 'CRUD Operations', null, 2, false),
    (v_module, 'Query / Update / Delete Records', null, 3, false),
    (v_module, 'Business Object Security', null, 4, false),
    (v_module, 'PROJECT: Employee Management Agent', null, 5, false);
  insert into public.modules (course_id, title, position) values (v_course, 'External REST Tool', 8) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'REST Basics', null, 0, false),
    (v_module, 'Authentication', null, 1, false),
    (v_module, 'GET / POST / PUT / DELETE', null, 2, false),
    (v_module, 'Headers & Query Parameters', null, 3, false),
    (v_module, 'Dynamic Variables', null, 4, false),
    (v_module, 'OAuth 2.0 & API Keys', null, 5, false),
    (v_module, 'PROJECT: Upload to UCM, call fscmRestApi, Azure DevOps, GitHub, OpenAI, Weather', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Runtime File Processor Tool', 9) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Read CSV', null, 0, false),
    (v_module, 'Read XML', null, 1, false),
    (v_module, 'Read Excel (.xlsx)', null, 2, false),
    (v_module, 'Read PDF', null, 3, false),
    (v_module, 'Read JSON', null, 4, false),
    (v_module, 'Read ZIP', null, 5, false),
    (v_module, 'PROJECT: Employee XML Upload, HDL Upload, Supplier Upload', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'MCP Tool', 10) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'What is MCP?', null, 0, false),
    (v_module, 'MCP Architecture', null, 1, false),
    (v_module, 'MCP Server & Client', null, 2, false),
    (v_module, 'GitHub MCP', null, 3, false),
    (v_module, 'Oracle MCP', null, 4, false),
    (v_module, 'Visual Studio MCP', null, 5, false),
    (v_module, 'Claude / ChatGPT MCP', null, 6, false),
    (v_module, 'PROJECT: GitHub, Oracle OIC and VS Code integrations', null, 7, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Workflow Agents', 11) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Workflow Overview', null, 0, false),
    (v_module, 'Workflow Designer', null, 1, false),
    (v_module, 'Start / Tool / Agent Nodes', null, 2, false),
    (v_module, 'Human Approval & Code Nodes', null, 3, false),
    (v_module, 'Decision & End Nodes', null, 4, false),
    (v_module, 'PROJECT: Invoice Approval Workflow', null, 5, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Hierarchical Agents', 12) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Supervisor Agent', null, 0, false),
    (v_module, 'Child Agents', null, 1, false),
    (v_module, 'Delegation', null, 2, false),
    (v_module, 'Tool Sharing', null, 3, false),
    (v_module, 'Context Passing', null, 4, false),
    (v_module, 'Multi-Agent Collaboration', null, 5, false),
    (v_module, 'PROJECT: HR AI Assistant (Leave, Payroll, Recruitment)', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'AI Agent Integrations', 13) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Oracle Fusion Cloud & OIC', null, 0, false),
    (v_module, 'REST & SOAP APIs', null, 1, false),
    (v_module, 'UCM & HDL', null, 2, false),
    (v_module, 'ATP (Autonomous DB) & OCI Services', null, 3, false),
    (v_module, 'GitHub & Azure DevOps', null, 4, false),
    (v_module, 'SharePoint, Teams & Slack', null, 5, false),
    (v_module, 'OpenAI / Claude & MCP Servers', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Oracle UCM Integration', 14) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'PROJECT: Upload File to UCM', null, 0, false),
    (v_module, 'PROJECT: Download File from UCM', null, 1, false),
    (v_module, 'PROJECT: Search Documents', null, 2, false),
    (v_module, 'PROJECT: Delete & Version Documents', null, 3, false),
    (v_module, 'PROJECT: AI Upload Agent — automated document lifecycle', null, 4, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Oracle HCM Projects', 15) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'PROJECT: Employee Search Agent', null, 0, false),
    (v_module, 'PROJECT: HDL Upload Agent', null, 1, false),
    (v_module, 'PROJECT: Department Creation Agent', null, 2, false),
    (v_module, 'PROJECT: Payroll Query Agent', null, 3, false),
    (v_module, 'PROJECT: Leave Management Agent', null, 4, false),
    (v_module, 'PROJECT: Recruitment Agent', null, 5, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Oracle ERP Projects', 16) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'PROJECT: Journal Import Agent (GL FBDI)', null, 0, false),
    (v_module, 'PROJECT: Supplier Creation Agent', null, 1, false),
    (v_module, 'PROJECT: Customer Creation Agent', null, 2, false),
    (v_module, 'PROJECT: Invoice Processing Agent', null, 3, false),
    (v_module, 'PROJECT: Expense Upload Agent', null, 4, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Oracle Integration Cloud + AI Agents', 17) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Invoke OIC from AI Agent', null, 0, false),
    (v_module, 'OIC REST & SOAP Integration', null, 1, false),
    (v_module, 'ATP Database Connection', null, 2, false),
    (v_module, 'SFTP File Transfer', null, 3, false),
    (v_module, 'Error Handling', null, 4, false),
    (v_module, 'Logging & Monitoring', null, 5, false),
    (v_module, 'PROJECT: End-to-End OIC + AI Integration', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Monitoring, Evaluation and Traceability (METRO)', 18) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Monitoring dashboard', null, 0, false),
    (v_module, 'Evaluation framework & Sets', null, 1, false),
    (v_module, 'Trace Logs', null, 2, false),
    (v_module, 'Token Usage analysis', null, 3, false),
    (v_module, 'Cost Analysis', null, 4, false),
    (v_module, 'Performance Tuning', null, 5, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Security', 19) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Roles & Privileges', null, 0, false),
    (v_module, 'OAuth 2.0 Configuration', null, 1, false),
    (v_module, 'JWT Token Management', null, 2, false),
    (v_module, 'API Security', null, 3, false),
    (v_module, 'Data Privacy Controls', null, 4, false),
    (v_module, 'AI Guardrails', null, 5, false),
    (v_module, 'Prompt Injection Prevention', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Deployment', 20) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Publish Agent', null, 0, false),
    (v_module, 'Versioning', null, 1, false),
    (v_module, 'Migration between environments', null, 2, false),
    (v_module, 'Export & Import', null, 3, false),
    (v_module, 'Production Deployment checklist', null, 4, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Troubleshooting', 21) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Prompt Issues', null, 0, false),
    (v_module, 'Tool Failures', null, 1, false),
    (v_module, 'REST Errors', null, 2, false),
    (v_module, 'Token Expiry handling', null, 3, false),
    (v_module, 'Debugging techniques', null, 4, false),
    (v_module, 'Common Errors & fixes', null, 5, false),
    (v_module, 'Authentication failures', null, 6, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Performance Optimization', 22) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Prompt Optimization', null, 0, false),
    (v_module, 'Token Optimization', null, 1, false),
    (v_module, 'Cost Optimization', null, 2, false),
    (v_module, 'Parallel Execution', null, 3, false),
    (v_module, 'Workflow Optimization', null, 4, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Real-Time Enterprise Projects', 23) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'UCM Upload Agent', null, 0, false),
    (v_module, 'HDL Upload Agent', null, 1, false),
    (v_module, 'Employee Search Agent', null, 2, false),
    (v_module, 'Leave Management Agent', null, 3, false),
    (v_module, 'Journal Import Agent', null, 4, false),
    (v_module, 'Supplier Creation Agent', null, 5, false),
    (v_module, 'GitHub AI Agent', null, 6, false),
    (v_module, 'Azure DevOps AI Agent', null, 7, false),
    (v_module, 'Email Automation Agent', null, 8, false),
    (v_module, 'Invoice Processing Agent', null, 9, false),
    (v_module, 'Resume Screening Agent', null, 10, false),
    (v_module, 'Oracle Fusion Support Agent', null, 11, false),
    (v_module, 'AI Knowledge Assistant (RAG)', null, 12, false),
    (v_module, 'RAG Document Assistant', null, 13, false),
    (v_module, 'Multi-Agent HR Assistant', null, 14, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Best Practices', 24) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'Prompt Design best practices', null, 0, false),
    (v_module, 'Tool Design principles', null, 1, false),
    (v_module, 'Security standards', null, 2, false),
    (v_module, 'Performance guidelines', null, 3, false),
    (v_module, 'Error Handling patterns', null, 4, false),
    (v_module, 'Reusable Agent design', null, 5, false),
    (v_module, 'Governance framework', null, 6, false),
    (v_module, 'Enterprise Architecture', null, 7, false);
  insert into public.modules (course_id, title, position) values (v_course, 'Bonus Modules', 25) returning id into v_module;
  insert into public.lessons (module_id, title, mux_playback_id, position, is_preview) values
    (v_module, 'MCP Deep Dive', null, 0, false),
    (v_module, 'Agent-to-Agent (A2A)', null, 1, false),
    (v_module, 'Invoke Async APIs', null, 2, false),
    (v_module, 'Human Approval Patterns', null, 3, false),
    (v_module, 'OCI Generative AI', null, 4, false),
    (v_module, 'BYO LLM', null, 5, false),
    (v_module, 'OpenAI Integration', null, 6, false),
    (v_module, 'Vector Database', null, 7, false),
    (v_module, 'RAG Implementation', null, 8, false),
    (v_module, 'Document Embedding', null, 9, false),
    (v_module, 'AI Agent Migration', null, 10, false),
    (v_module, 'AI Agent Templates', null, 11, false),
    (v_module, 'Oracle AI Roadmap 2026', null, 12, false);
  insert into public.quizzes (course_id, title, description, position) values (v_course, 'Foundations Check (Modules 1–5)', 'Test your understanding of AI fundamentals and agent design.', 0) returning id into v_quiz;
  insert into public.quiz_questions (quiz_id, prompt, type, options, correct, points, position) values
    (v_quiz, 'Which agent orchestrates multiple sub-agents and decides routing?', 'single', '["Utility Agent","Supervisor Agent","Persona-based Agent","Tool User Agent"]'::jsonb, '[1]'::jsonb, 1, 0),
    (v_quiz, 'Which patterns involve more than one agent? (select all)', 'multiple', '["Single Agent","Hierarchical Agents","Agent-to-Agent (A2A)","Multi-Agent"]'::jsonb, '[1,2,3]'::jsonb, 2, 1),
    (v_quiz, 'When is a Human-in-the-Loop pattern used?', 'single', '["For simple one-tool tasks","When approval is required before an action","To translate text","To reduce token cost"]'::jsonb, '[1]'::jsonb, 1, 2);
  insert into public.quizzes (course_id, title, description, position) values (v_course, 'Tools & Integrations (Modules 7–14)', 'Check your knowledge of AI Agent tools and enterprise integrations.', 1) returning id into v_quiz;
  insert into public.quiz_questions (quiz_id, prompt, type, options, correct, points, position) values
    (v_quiz, 'Which tool performs CRUD on Oracle Fusion Business Objects?', 'single', '["External REST Tool","Business Object Tool","MCP Tool","Calculator Tool"]'::jsonb, '[1]'::jsonb, 1, 0),
    (v_quiz, 'Which file formats can the Runtime File Processor read? (select all)', 'multiple', '["CSV","PDF","ZIP","Excel"]'::jsonb, '[0,1,2,3]'::jsonb, 2, 1),
    (v_quiz, 'MCP lets Oracle AI Studio connect to which of these?', 'multiple', '["GitHub","VS Code","Claude / ChatGPT","None of these"]'::jsonb, '[0,1,2]'::jsonb, 2, 2);
  insert into public.assignments (course_id, title, instructions, position) values (v_course, 'Build an Employee Management Agent', 'Using the Business Object Tool, build an agent that can search employees by name/department/role, update employee records via chat, and query leave balances. Secure BO access with role-based permissions. Submit a short write-up and a link to a recording or screenshots.', 0);
  insert into public.assignments (course_id, title, instructions, position) values (v_course, 'Invoice Approval Workflow', 'Design a Workflow Agent that receives invoice data, validates it against a PO (2-way/3-way match), routes to an approver via a Human Approval node, then posts a journal and emails confirmation on approval (or notifies the submitter on rejection). Submit your workflow export and notes.', 1);
  insert into public.assignments (course_id, title, instructions, position) values (v_course, 'Multi-Agent HR Assistant (Capstone)', 'Build a Supervisor agent that routes to Leave, Payroll and Recruitment specialist agents, each with dedicated BO/REST tools and shared context for multi-turn conversations. Submit a link to your working demo.', 2);
end $$;
